import {
  REACT_NATIVE_SUPABASE_URL,
  REACT_NATIVE_SUPABASE_ANON_KEY,
  REACT_NATIVE_OAUTH_CLIENT_ID,
  REACT_NATIVE_OAUTH_WEB_CLIENT_ID,
} from '@env';

export default {
  SUPABASE_URL: REACT_NATIVE_SUPABASE_URL,
  SUPABASE_ANON_KEY: REACT_NATIVE_SUPABASE_ANON_KEY,
  OAUTH_CLIENT_ID: REACT_NATIVE_OAUTH_CLIENT_ID,
  OAUTH_CLIENT_WEB_ID: REACT_NATIVE_OAUTH_WEB_CLIENT_ID,
};
