import {
  REACT_NATIVE_OAUTH_CLIENT_ID,
  REACT_NATIVE_OAUTH_WEB_CLIENT_ID,
} from '@env';

export default {
  OAUTH_CLIENT_ID: REACT_NATIVE_OAUTH_CLIENT_ID,
  OAUTH_CLIENT_WEB_ID: REACT_NATIVE_OAUTH_WEB_CLIENT_ID,
};
